ssh_key_filename: ~/.ssh/id_rsa
admin_id: admin
admin_pw: Secret123
dirman_id: '"cn=Directory Manager"'
dirman_pw: Secret123
dns_forwarder: 10.11.5.19
domains:
  - name: testrelm.test
    type: ipa
    hosts:
      - name: master.testrelm.test
        external_hostname: hostname1
        role: master
  - name: ipaad2012r2.test
    type: ad
    hosts:
      - name: idm-qe-ipa-win3.ipaad2012r2.test
        external_hostname: idm-qe-ipa-win3.ipaad2012r2.test
        ip: 10.8.63.43
        role: ad
        username: 'Administrator'
        password: 'Secret123'
        host_type: 'windows'
